# Generated by Django 4.1.1 on 2022-10-20 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_feedback_time_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal_details",
            name="resume_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
