# Generated by Django 4.1.1 on 2022-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_personal_details_resume_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal_details",
            name="resume_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
