# Generated by Django 4.1.1 on 2022-10-07 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_award_user_remove_certificate_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="interest",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="personal_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.personal_details"
            ),
        ),
    ]
