# Generated by Django 4.1.1 on 2022-10-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_award_personal_detail_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="Skills",
        ),
    ]
