# Generated by Django 4.1.1 on 2022-10-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_skill_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="information",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
