# Generated by Django 4.1.1 on 2022-10-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_link_award_award_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="level",
            new_name="language_level",
        ),
        migrations.RenameField(
            model_name="skills",
            old_name="level",
            new_name="skilll_level",
        ),
    ]
