# Generated by Django 4.1.1 on 2022-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_level_language_language_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skills",
            old_name="skilll_level",
            new_name="skill_level",
        ),
    ]
