# Generated by Django 4.1.1 on 2022-10-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_skills_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.skill_level",
            ),
        ),
    ]
