# Generated by Django 4.1.1 on 2022-10-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_skills_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personal_details",
            old_name="sanpchat",
            new_name="snapchat",
        ),
    ]
