# Generated by Django 4.1.1 on 2022-10-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_description_education_education_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="job_title",
            new_name="experience_job_title",
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="email",
            new_name="reference_email",
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="job_title",
            new_name="reference_job_title",
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="phone",
            new_name="reference_phone",
        ),
    ]
