# Generated by Django 4.1.1 on 2022-10-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_sanpchat_personal_details_snapchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="hide_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experience",
            name="hide_month",
            field=models.BooleanField(default=False),
        ),
    ]
