# Generated by Django 4.1.1 on 2022-10-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_job_title_experience_experience_job_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="award",
            old_name="date",
            new_name="award_date",
        ),
        migrations.RenameField(
            model_name="award",
            old_name="description",
            new_name="award_description",
        ),
    ]
