# Generated by Django 4.1.1 on 2022-10-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_experience_hide_day_experience_hide_month"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="hide_day",
            new_name="month_year_only",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="hide_month",
            new_name="year_only",
        ),
    ]
