# Generated by Django 4.1.1 on 2022-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_hide_day_experience_month_year_only_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="company_location",
        ),
        migrations.AddField(
            model_name="education",
            name="month_year_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="year_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="month_year_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="year_only",
            field=models.BooleanField(default=False),
        ),
    ]
