# Generated by Django 4.1.1 on 2022-10-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_date_award_award_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="additional_information",
            new_name="certificate_additional_information",
        ),
        migrations.RenameField(
            model_name="interest",
            old_name="additional_information",
            new_name="interest_additional_information",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="additional_information",
            new_name="language_additional_information",
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="description",
            new_name="organisation_description",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="date",
            new_name="publication_date",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="description",
            new_name="publication_description",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="title",
            new_name="publication_title",
        ),
    ]
