# Generated by Django 4.1.1 on 2022-10-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0012_rename_additional_information_certificate_certificate_additional_information_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="skills",
            old_name="skill",
            new_name="skill_name",
        ),
    ]
