# Generated by Django 4.1.1 on 2022-10-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_experience_company_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="description",
            new_name="experience_description",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="description",
            new_name="project_description",
        ),
    ]
