# Generated by Django 4.1.1 on 2022-10-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_rename_description_experience_experience_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="additional_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="experience_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interest",
            name="additional_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="summary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
