# Generated by Django 4.1.1 on 2022-10-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_rename_skill_skills_skill_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skills",
            old_name="information",
            new_name="skill_information",
        ),
    ]
