# Generated by Django 4.1.1 on 2022-10-14 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_award_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="school",
            field=models.CharField(max_length=70),
        ),
    ]
