# Generated by Django 4.1.1 on 2022-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_information_skills_skill_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="experience_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Experience Start Date"
            ),
        ),
    ]
