# Generated by Django 4.1.1 on 2022-10-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_education_degree_alter_education_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="additional_information",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.language_level",
            ),
        ),
    ]
