# Generated by Django 4.1.1 on 2022-11-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_award_award_month_year_only_award_award_year_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_month_year_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="publication_year_only",
            field=models.BooleanField(default=False),
        ),
    ]
