# Generated by Django 4.1.1 on 2022-10-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_language_additional_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="month_year_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="year_only",
            field=models.BooleanField(default=False),
        ),
    ]
