# Generated by Django 4.1.1 on 2022-10-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_organisation_month_year_only_organisation_year_only"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference",
            old_name="name",
            new_name="reference_name",
        ),
    ]
