# Generated by Django 4.1.1 on 2022-10-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_rename_name_reference_reference_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation",
            old_name="organization",
            new_name="organisation",
        ),
    ]
