from django.urls import path
from . import views
from .forms import PasswordResetConfirmForm, PasswordResetForm
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", views.home, name="home"),
    path("personal-details/", views.person_details, name="person_details"),
    path("skill/", views.addSkill, name="addSkill"),
    path("skill/<str:pk>", views.getSkill, name="getSkill"),
    path("experience/<str:pk>", views.getExperience, name="getExperience"),
    path("update-skill/<str:pk>", views.updateSkill, name="updateSkill"),
    path("profile/", views.profile, name="profile"),
    path("delete-skill/<str:pk>", views.deleteSkill, name="deleteSkill"),
    path("experience/", views.addExperience, name="addExperience"),
    path("update-experience/<str:pk>", views.updateExperience, name="updateExperience"),
    path("delete-experience/<str:pk>", views.deleteExperience, name="deleteExperience"),
    path("project/", views.addProject, name="addProject"),
    path("project/<str:pk>", views.getProject, name="getProject"),
    path("update-project/<str:pk>", views.updateProject, name="updateProject"),
    path("delete-project/<str:pk>", views.deleteProject, name="deleteProject"),
    path("education/", views.addEducation, name="addEducation"),
    path("education/<str:pk>", views.getEducation, name="getEducation"),
    path("update-education/<str:pk>", views.updateEducation, name="updateEducation"),
    path("delete-education/<str:pk>", views.deleteEducation, name="deleteEducation"),
    path("language/", views.addLanguage, name="addLanguage"),
    path("language/<str:pk>", views.getLanguage, name="getLanguage"),
    path("update-language/<str:pk>", views.updateLanguage, name="updateLanguage"),
    path("delete-language/<str:pk>", views.deleteLanguage, name="deleteLanguage"),
    path("reference/", views.addReference, name="addReference"),
    path("reference/<str:pk>", views.getReference, name="getReference"),
    path("update-reference/<str:pk>", views.updateReference, name="updateReference"),
    path("delete-reference/<str:pk>", views.deleteReference, name="deleteReference"),
    path("award/", views.addAward, name="addAward"),
    path("award/<str:pk>", views.getAward, name="getAward"),
    path("update-award/<str:pk>", views.updateAward, name="updateAward"),
    path("delete-award/<str:pk>", views.deleteAward, name="deleteAward"),
    path("organisation/", views.addOrganisation, name="addOrganisation"),
    path("organisation/<str:pk>", views.getOrganisation, name="getOrganisation"),
    path("update-organisation/<str:pk>", views.updateOrganisation, name="updateOrganisation"),
    path("delete-organisation/<str:pk>", views.deleteOrganisation, name="deleteOrganisation"),
    path("certificate/", views.addCertificate, name="addCertificate"),
    path("certificate/<str:pk>", views.getCertificate, name="getCertificate"),
    path("update-certificate/<str:pk>", views.updateCertificate, name="updateCertificate"),
    path("delete-certificate/<str:pk>", views.deleteCertificate, name="deleteCertificate"),
    path("interest/", views.addInterest, name="addInterest"),
    path("interest/<str:pk>", views.getInterest, name="getInterest"),
    path("update-interest/<str:pk>", views.updateInterest, name="updateInterest"),
    path("delete-interest/<str:pk>", views.deleteInterest, name="deleteInterest"),
    path("publication/", views.addPublication, name="addPublication"),
    path("publication/<str:pk>", views.getPublication, name="getPublication"),
    path("update-publication/<str:pk>", views.updatePublication, name="updatePublication"),
    path("delete-publication/<str:pk>", views.deletePublication, name="deletePublication"),
    path("register/", views.account_register, name="register"),
    path("login/", views.account_login, name="login"),
    path("logout/", views.account_logout, name="logout"),
    path("delete/", views.account_delete, name="delete_account"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/user/password-reset-form.html",
            success_url="password-reset-email-confirm",
            email_template_name="account/user/password-reset-email.html",
            form_class=PasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/user/password-reset-confirm.html",
            success_url="/account/password-reset-complete/",
            form_class=PasswordResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/password-reset-email-confirm/",
        TemplateView.as_view(template_name="account/user/password-reset-success.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        TemplateView.as_view(template_name="account/user/password-reset-success.html"),
        name="password_reset_complete",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/user/forgot-password.html", success_url="/"
        ),
        name="change_password",
    ),
]
