# Generated by Django 3.2.4 on 2021-08-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('education', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=1000)),
                ('experience', models.TextField(max_length=2000)),
            ],
        ),
    ]
