# Generated by Django 3.2.4 on 2021-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
