# Generated by Django 3.2.4 on 2021-08-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0003_auto_20210817_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
