# Generated by Django 3.2.4 on 2021-09-01 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_resume', '0004_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='summary',
            field=models.TextField(default='About Me'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_held', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=100)),
                ('year_from', models.CharField(max_length=20)),
                ('year_to', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
