# Generated by Django 3.2.4 on 2021-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0005_auto_20210818_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('source_code', models.CharField(blank=True, max_length=150, null=True)),
                ('live', models.CharField(blank=True, max_length=150, null=True)),
                ('info', models.TextField()),
            ],
        ),
    ]
