# Generated by Django 3.2.4 on 2021-08-19 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
