# Generated by Django 3.2.4 on 2021-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0007_auto_20210903_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='site',
            field=models.CharField(blank=True, default='ho', max_length=700, null=True),
        ),
    ]
