# Generated by Django 3.2.4 on 2021-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0008_person_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='site',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
