# Generated by Django 3.2.4 on 2021-09-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0010_auto_20210903_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
