# Generated by Django 3.2.4 on 2021-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0011_delete_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.TextField(max_length=200),
        ),
    ]
