# Generated by Django 3.2.4 on 2021-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0012_alter_project_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year_to',
            field=models.DateField(),
        ),
    ]
